name: events_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: "^4.1.2"
  firebase_core: "0.7.0"
  firebase_auth: "^0.20.0+1"
  flushbar: ^1.10.4
  cloud_firestore: "^0.16.0"
  firebase_storage: "^7.0.0"
  path_provider: ^1.6.27
  image_picker: ^0.6.6+5
  provider: ^4.3.2+3
  cupertino_icons: ^1.0.1
  geolocator: ^6.1.14
  geocoder: ^0.2.1
  flutter_datetime_picker: ^1.5.0
  map_pin_picker: ^0.0.1
  google_maps_flutter: ^1.1.1
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

